'use strict';

/**
 * NRD · chainEngine.js — Master Execution Chain Loop Engine.
 * 
 * ROLE:
 * Executes the multi-phase execution plan generated by the Department Head (Agent #1).
 * 
 * FEATURES:
 * 1. Sequential & parallel phase dispatch based on dh_execution_plan.
 * 2. Registry-based agent execution with graceful skipping of pending agents.
 * 3. Approval Gate enforcement:
 *    - If auto_approve is false, run status transitions to 'awaiting_approval' after Phase 1.
 *    - Persists chain_state so execution halts cleanly and awaits user interaction.
 * 4. Run Controls:
 *    - startRun(runId) / resumeRun(runId)
 *    - approveRun(runId, approvedNiches)
 *    - pauseRun(runId)
 *    - resumePausedRun(runId)
 *    - cancelRun(runId)
 * 5. Automatic retry policy:
 *    - Max 2 retries per agent with exponential backoff before marking failed or continuing.
 *    - Critical vs non-critical failure isolation.
 * 6. App Restart Recovery:
 *    - On launch, resumes active runs or preserves runs in 'awaiting_approval'.
 * 7. Live IPC Telemetry:
 *    - Emits real-time state and log events to Electron renderer windows.
 */

const { EventEmitter } = require('node:events');
const db = require('../db');
const agentRegistry = require('./agentRegistry');

// Ensure registered agents (1–3) are loaded into Agent Registry
try {
  require('../agents/criteriaParser');
  require('../agents/departmentHead');
  require('../agents/qualitySupervisor');
} catch {
  // Graceful fallback if agent files are initialized out of order in test runners
}

class ChainEngine extends EventEmitter {
  constructor() {
    super();
    /**
     * Active running run IDs with cancellation/pause signals.
     * @type {Map<number, { isPaused: boolean, isCancelled: boolean, currentPhase: string, currentAgent: number | null }>}
     */
    this.activeRuns = new Map();
    this.browserEngine = null;
  }

  getBrowserEngine() {
    if (!this.browserEngine) {
      try {
        const engine = require('./index');
        this.browserEngine = engine.browserEngine;
      } catch {
        this.browserEngine = {
          log: (lvl, msg) => console.log(`[NRD · ${lvl.toUpperCase()}] ${msg}`),
          emit: () => {},
        };
      }
    }
    return this.browserEngine;
  }

  /**
   * Starts or triggers end-to-end execution of a research run.
   * If the run is in 'pending', auto-runs criteria parsing and builds plan first.
   * 
   * @param {number} runId
   * @param {object} [options={}]
   * @returns {Promise<{ success: boolean, status: string, error?: string }>}
   */
  async startRun(runId, options = {}) {
    const runIdNum = Number(runId);
    const dbInstance = db.getDb();
    const engine = this.getBrowserEngine();

    // Check if already actively running
    if (this.activeRuns.has(runIdNum) && !this.activeRuns.get(runIdNum).isPaused) {
      return { success: true, status: 'already_running', run_id: runIdNum };
    }

    const run = dbInstance.prepare('SELECT * FROM research_runs WHERE id = ?').get(runIdNum);
    if (!run) {
      throw new Error(`Run #${runIdNum} not found in database.`);
    }

    engine.log('info', `🚀 Chain Engine: Starting execution for Run #${runIdNum} (status: ${run.status})…`);

    // 1. Ensure Agent #2 (Criteria Parser) has run
    let criteriaRow = dbInstance.prepare('SELECT * FROM run_criteria WHERE run_id = ?').get(runIdNum);
    if (!criteriaRow || !criteriaRow.parsed_brief) {
      engine.log('info', `📋 Chain Engine: Triggering Agent #2 (Criteria Parser) for Run #${runIdNum}…`);
      const ag2Spec = { number: 2, name: 'Criteria Parser Agent', critical: true };
      const parseResult = await this._executeAgentWithRetry(runIdNum, ag2Spec);
      if (parseResult?.failed || parseResult?.error) {
        dbInstance.prepare(`UPDATE research_runs SET status = 'failed', error_summary = ? WHERE id = ?`)
          .run(parseResult?.error || 'Criteria parse failed', runIdNum);
        return { success: false, status: 'failed', error: parseResult?.error };
      }
    }

    // 2. Ensure Agent #1 (Department Head) has built plan
    let plan = null;
    if (run.dh_execution_plan) {
      try {
        plan = typeof run.dh_execution_plan === 'string' ? JSON.parse(run.dh_execution_plan) : run.dh_execution_plan;
      } catch {
        plan = null;
      }
    }

    if (!plan) {
      engine.log('info', `👑 Chain Engine: Triggering Agent #1 (Department Head) for Run #${runIdNum}…`);
      const ag1Spec = { number: 1, name: 'Department Head Agent', critical: true };
      await this._executeAgentWithRetry(runIdNum, ag1Spec);
      const runRefreshed = dbInstance.prepare('SELECT dh_execution_plan FROM research_runs WHERE id = ?').get(runIdNum);
      try {
        plan = typeof runRefreshed?.dh_execution_plan === 'string' ? JSON.parse(runRefreshed.dh_execution_plan) : runRefreshed?.dh_execution_plan;
      } catch {
        plan = null;
      }
    }

    // Mark active in memory
    this.activeRuns.set(runIdNum, {
      isPaused: false,
      isCancelled: false,
      currentPhase: 'discovery',
      currentAgent: null,
    });

    // Update run status in DB
    const nowIso = new Date().toISOString();
    dbInstance.prepare(`
      UPDATE research_runs 
      SET status = 'discovery', started_at = COALESCE(started_at, ?), updated_at = datetime('now')
      WHERE id = ?
    `).run(nowIso, runIdNum);

    this.emitStatusUpdate(runIdNum, 'discovery');

    // Execute chain loop
    const executionPromise = this._executeChain(runIdNum, plan, options).catch((err) => {
      engine.log('error', `❌ Chain Engine: Fatal execution error on Run #${runIdNum}: ${err.message}`);
      dbInstance.prepare(`
        UPDATE research_runs 
        SET status = 'failed', error_summary = ?, updated_at = datetime('now')
        WHERE id = ?
      `).run(err.message, runIdNum);
      this.emitStatusUpdate(runIdNum, 'failed');
      this.activeRuns.delete(runIdNum);
    });

    if (options.sync) {
      await executionPromise;
      const latestRun = dbInstance.prepare('SELECT status FROM research_runs WHERE id = ?').get(runIdNum);
      return { success: true, status: latestRun?.status || 'completed', run_id: runIdNum };
    }

    return { success: true, status: 'discovery', run_id: runIdNum };
  }

  /**
   * Internal chain execution loop across all phases.
   * 
   * @private
   * @param {number} runId
   * @param {object} plan
   * @param {object} options
   */
  async _executeChain(runId, plan, options = {}) {
    const dbInstance = db.getDb();
    const engine = this.getBrowserEngine();
    const activeControl = this.activeRuns.get(runId);

    const phases = plan.phases || [];

    for (let pIdx = 0; pIdx < phases.length; pIdx++) {
      const phaseObj = phases[pIdx];
      const phaseKey = phaseObj.phase; // 'discovery' | 'deep_research' | 'scoring' | 'qa_reporting'

      if (activeControl.isCancelled) {
        engine.log('warn', `🛑 Chain Engine: Run #${runId} was cancelled before phase: ${phaseKey}`);
        dbInstance.prepare(`UPDATE research_runs SET status = 'cancelled', updated_at = datetime('now') WHERE id = ?`).run(runId);
        this.emitStatusUpdate(runId, 'cancelled');
        this.activeRuns.delete(runId);
        return;
      }

      if (activeControl.isPaused) {
        engine.log('info', `⏸️ Chain Engine: Run #${runId} paused before phase: ${phaseKey}`);
        this._saveChainState(runId, { phase: phaseKey, step: 0 });
        return;
      }

      // Map internal phase identifiers to valid research_runs CHECK constraint status
      const phaseStatusMap = {
        discovery: 'discovery',
        deep_research: 'deep_research',
        scoring: 'scoring',
        qa: 'qa',
        reporting: 'reporting',
        qa_reporting: 'qa',
      };
      const runStatusValue = phaseStatusMap[phaseKey] || 'deep_research';

      // Update current run status
      activeControl.currentPhase = phaseKey;
      dbInstance.prepare(`UPDATE research_runs SET status = ?, updated_at = datetime('now') WHERE id = ?`).run(runStatusValue, runId);
      this.emitStatusUpdate(runId, runStatusValue);

      engine.log('info', `▶️ Chain Engine: Executing ${phaseObj.name} (Run #${runId})…`);

      // Execute each agent in the phase
      const agents = phaseObj.agents || [];
      for (let aIdx = 0; aIdx < agents.length; aIdx++) {
        const agentSpec = agents[aIdx];
        const agentNum = agentSpec.number;

        if (activeControl.isCancelled) {
          engine.log('warn', `🛑 Chain Engine: Run #${runId} cancelled at Agent #${agentNum}`);
          dbInstance.prepare(`UPDATE research_runs SET status = 'cancelled', updated_at = datetime('now') WHERE id = ?`).run(runId);
          this.emitStatusUpdate(runId, 'cancelled');
          this.activeRuns.delete(runId);
          return;
        }

        if (activeControl.isPaused) {
          engine.log('info', `⏸️ Chain Engine: Run #${runId} paused at Agent #${agentNum}`);
          this._saveChainState(runId, { phase: phaseKey, step: aIdx, agentNumber: agentNum });
          return;
        }

        activeControl.currentAgent = agentNum;
        await this._executeAgentWithRetry(runId, agentSpec);
      }

      // Check for Approval Gate after Phase 1 (discovery)
      if (phaseKey === 'discovery') {
        const runRecord = dbInstance.prepare('SELECT auto_approve, approval_gate_passed FROM research_runs WHERE id = ?').get(runId);
        const autoApprove = Boolean(runRecord && runRecord.auto_approve);
        const alreadyApproved = Boolean(runRecord && runRecord.approval_gate_passed);

        if (!autoApprove && !alreadyApproved) {
          // Pause execution and enter 'awaiting_approval'
          engine.log('info', `🛑 Chain Engine: Reached Approval Gate for Run #${runId}. Halting for user review.`);
          this._saveChainState(runId, { phase: 'deep_research', step: 0, waitingForApproval: true });

          dbInstance.prepare(`
            UPDATE research_runs 
            SET status = 'awaiting_approval', updated_at = datetime('now')
            WHERE id = ?
          `).run(runId);

          this.emitStatusUpdate(runId, 'awaiting_approval');
          this.activeRuns.delete(runId);
          return;
        } else {
          engine.log('info', `⚡ Chain Engine: Approval Gate auto-passed for Run #${runId} (auto_approve=${autoApprove})`);
          dbInstance.prepare(`
            UPDATE research_runs 
            SET approval_gate_passed = 1, updated_at = datetime('now')
            WHERE id = ?
          `).run(runId);
        }
      }
    }

    // All phases complete!
    const completedAt = new Date().toISOString();
    dbInstance.prepare(`
      UPDATE research_runs 
      SET status = 'completed', completed_at = ?, chain_state = NULL, updated_at = datetime('now')
      WHERE id = ?
    `).run(completedAt, runId);

    engine.log('info', `🏁 Chain Engine: Run #${runId} successfully completed all phases!`);
    this.emitStatusUpdate(runId, 'completed');
    this.activeRuns.delete(runId);
  }

  /**
   * Executes a single agent with retry policy and registry lookup.
   * 
   * @private
   * @param {number} runId
   * @param {object} agentSpec
   */
  async _executeAgentWithRetry(runId, agentSpec) {
    const dbInstance = db.getDb();
    const engine = this.getBrowserEngine();
    const agentNum = agentSpec.number;
    const isCritical = Boolean(agentSpec.critical);

    const isRegistered = agentRegistry.isRegistered(agentNum);

    if (!isRegistered) {
      // Gracefully skip pending agent (built in future prompts)
      engine.log('info', `⏩ Chain Engine: Agent #${agentNum} (${agentSpec.name}) is pending implementation in a later prompt — skipped gracefully.`);
      
      // Keep agent_status as idle/pending or update summary
      dbInstance.prepare(`
        UPDATE agent_status 
        SET output_summary = 'Pending implementation in later prompt — skipped gracefully.',
            updated_at = datetime('now')
        WHERE run_id = ? AND agent_number = ?
      `).run(runId, agentNum);

      this.emitAgentUpdate(runId, agentNum, 'idle');
      return { skipped: true, reason: 'pending_implementation' };
    }

    // Agent is registered! Execute with retry policy and Quality Supervisor interceptor
    const regAgent = agentRegistry.get(agentNum);
    const qualitySupervisor = require('../agents/qualitySupervisor');
    const maxRetries = 2;
    let attempt = 0;
    let lastErr = null;
    let reviewRound = 1;
    let currentQsFeedback = null;

    const startedAt = new Date().toISOString();
    const t0 = Date.now();

    while (attempt <= maxRetries) {
      try {
        dbInstance.prepare(`
          UPDATE agent_status 
          SET status = 'running', started_at = COALESCE(started_at, ?), retry_count = ?, updated_at = datetime('now')
          WHERE run_id = ? AND agent_number = ?
        `).run(startedAt, attempt, runId, agentNum);

        this.emitAgentUpdate(runId, agentNum, 'running');

        const logMsg = currentQsFeedback
          ? `🤖 Chain Engine: Re-invoking Agent #${agentNum} (${regAgent.name}) [QS Send-back Round ${reviewRound - 1}]…`
          : `🤖 Chain Engine: Invoking Agent #${agentNum} (${regAgent.name}) [attempt ${attempt + 1}/${maxRetries + 1}]…`;
        engine.log('info', logMsg);

        const runRow = dbInstance.prepare('SELECT * FROM research_runs WHERE id = ?').get(runId);
        const criteriaRow = dbInstance.prepare('SELECT * FROM run_criteria WHERE run_id = ?').get(runId);
        let parsedBrief = null;
        try {
          if (criteriaRow && criteriaRow.parsed_brief) {
            parsedBrief = JSON.parse(criteriaRow.parsed_brief);
          }
        } catch {
          // ignore
        }

        const context = {
          runId,
          agentNumber: agentNum,
          spec: agentSpec,
          db: dbInstance,
          engine,
          run: runRow,
          brief: parsedBrief,
          qs_feedback: currentQsFeedback,
        };

        const result = await regAgent.handler(context);

        // Quality Supervisor Interceptor (Agent #3 does NOT review itself)
        if (agentNum !== 3 && !result?.skipped) {
          const qsReview = await qualitySupervisor.reviewOutput({
            runId,
            agentNumber: agentNum,
            output: result,
            context,
            reviewRound,
            engine,
          });

          if (qsReview.verdict === 'send_back') {
            // Check run-level safety valve (max 10 total send-backs per run)
            const totalRunSendbacks = dbInstance.prepare(`
              SELECT COUNT(*) as count FROM quality_reviews
              WHERE run_id = ? AND verdict = 'send_back'
            `).get(runId)?.count || 0;

            if (totalRunSendbacks >= 10) {
              engine.log('warn', `🛑 Quality Supervisor: Max 10 total send-backs reached for Run #${runId}. Halting execution.`);
              dbInstance.prepare(`
                UPDATE research_runs 
                SET status = 'paused', updated_at = datetime('now')
                WHERE id = ?
              `).run(runId);

              dbInstance.prepare(`
                UPDATE agent_status 
                SET status = 'retrying', output_summary = 'QS safety valve triggered: max 10 total send-backs reached. Run paused.', updated_at = datetime('now')
                WHERE run_id = ? AND agent_number = ?
              `).run(runId, agentNum);

              this.emitStatusUpdate(runId, 'paused');
              this.emitAgentUpdate(runId, agentNum, 'retrying');
              return { sendBack: true, paused: true, reason: 'max_run_sendbacks' };
            }

            // Check agent-level send-back count (max 2 send-backs per agent per run)
            const agentSendbacks = dbInstance.prepare(`
              SELECT COUNT(*) as count FROM quality_reviews
              WHERE run_id = ? AND agent_number = ? AND verdict = 'send_back'
            `).get(runId, agentNum)?.count || 0;

            if (agentSendbacks <= 2) {
              reviewRound++;
              currentQsFeedback = qsReview.feedback;

              dbInstance.prepare(`
                UPDATE agent_status 
                SET status = 'retrying', output_summary = ?, updated_at = datetime('now')
                WHERE run_id = ? AND agent_number = ?
              `).run(`QS send-back round ${agentSendbacks}: ${qsReview.feedback}`, runId, agentNum);

              this.emitAgentUpdate(runId, agentNum, 'retrying');
              await new Promise((r) => setTimeout(r, 200));
              continue;
            } else {
              qsReview.verdict = 'escalated';
            }
          }

          if (qsReview.verdict === 'escalated') {
            const finishedAt = new Date().toISOString();
            dbInstance.prepare(`
              UPDATE agent_status 
              SET status = 'failed', finished_at = ?, output_summary = ?, updated_at = datetime('now')
              WHERE run_id = ? AND agent_number = ?
            `).run(finishedAt, `QS escalated after 2 send-backs: ${qsReview.feedback}`, runId, agentNum);

            this.emitAgentUpdate(runId, agentNum, 'failed');

            if (isCritical || regAgent.meta?.isCritical) {
              throw new Error(`Critical Agent #${agentNum} (${agentSpec.name}) escalated by Quality Supervisor: ${qsReview.feedback}`);
            } else {
              engine.log('warn', `⚠️ Non-critical Agent #${agentNum} escalated by QS. Proceeding with remaining chain.`);
              return { failed: true, escalated: true, error: qsReview.feedback };
            }
          }
        }

        const finishedAt = new Date().toISOString();
        const durationMs = Date.now() - t0;

        dbInstance.prepare(`
          UPDATE agent_status 
          SET status = 'done', 
              finished_at = ?,
              last_error = NULL,
              output_summary = ?,
              output_payload = ?,
              updated_at = datetime('now')
          WHERE run_id = ? AND agent_number = ?
        `).run(
          finishedAt,
          typeof result === 'object' && result?.summary ? result.summary : `Executed successfully`,
          typeof result === 'object' ? JSON.stringify(result) : String(result),
          runId,
          agentNum
        );

        this.emitAgentUpdate(runId, agentNum, 'done');

        // Also update Agent #3 (Quality Supervisor) status row
        try {
          const summary = db.getQualitySummary(runId);
          dbInstance.prepare(`
            UPDATE agent_status
            SET status = 'done',
                finished_at = ?,
                output_summary = ?,
                updated_at = datetime('now')
            WHERE run_id = ? AND agent_number = 3
          `).run(finishedAt, `QS Active: ${summary.totalPassed}/${summary.totalReviews} passed, ${summary.totalSendBacks} send-backs`, runId);
          this.emitAgentUpdate(runId, 3, 'done');
        } catch {
          // ignore
        }

        // Log timing
        try {
          db.insert('timing_logs', {
            run_id: runId,
            task_ref: `agent_${agentNum}_run_${runId}`,
            agent_number: agentNum,
            operation: `agent_exec_${agentNum}`,
            started_at: startedAt,
            ended_at: finishedAt,
            duration_ms: Math.max(1, durationMs),
            cache_hit: 0,
          });
        } catch {
          // ignore
        }

        return result;
      } catch (err) {
        attempt++;
        lastErr = err;
        engine.log('warn', `⚠️ Chain Engine: Agent #${agentNum} attempt ${attempt} failed: ${err.message}`);

        if (attempt <= maxRetries) {
          dbInstance.prepare(`
            UPDATE agent_status 
            SET status = 'retrying', last_error = ?, updated_at = datetime('now')
            WHERE run_id = ? AND agent_number = ?
          `).run(err.message, runId, agentNum);

          this.emitAgentUpdate(runId, agentNum, 'retrying');
          // Exponential backoff: 300ms, 600ms
          await new Promise((r) => setTimeout(r, attempt * 300));
        }
      }
    }

    // All retries exhausted
    const finishedAt = new Date().toISOString();
    dbInstance.prepare(`
      UPDATE agent_status 
      SET status = 'failed', 
          finished_at = ?,
          last_error = ?,
          updated_at = datetime('now')
      WHERE run_id = ? AND agent_number = ?
    `).run(finishedAt, lastErr?.message || 'Execution error', runId, agentNum);

    this.emitAgentUpdate(runId, agentNum, 'failed');

    if (isCritical) {
      throw new Error(`Critical Agent #${agentNum} (${agentSpec.name}) failed after ${maxRetries} retries: ${lastErr?.message}`);
    } else {
      engine.log('warn', `⚠️ Chain Engine: Non-critical Agent #${agentNum} failed. Proceeding with remaining chain.`);
      return { failed: true, error: lastErr?.message };
    }
  }

  /**
   * Approves a run waiting at the Approval Gate and resumes execution into Phase 2 (Deep Research).
   * 
   * @param {number} runId
   * @param {Array<object>} [approvedNiches=[]]
   * @returns {Promise<{ success: boolean, status: string }>}
   */
  async approveRun(runId, approvedNiches = [], options = {}) {
    const runIdNum = Number(runId);
    const dbInstance = db.getDb();
    const engine = this.getBrowserEngine();

    engine.log('info', `✅ Chain Engine: Approval received for Run #${runIdNum}! Resuming into Deep Research…`);

    // 1. Mark approval_gate_passed = 1
    dbInstance.prepare(`
      UPDATE research_runs 
      SET approval_gate_passed = 1,
          status = 'deep_research',
          updated_at = datetime('now')
      WHERE id = ?
    `).run(runIdNum);

    // 2. Fetch execution plan
    const run = dbInstance.prepare('SELECT * FROM research_runs WHERE id = ?').get(runIdNum);
    let plan = null;
    try {
      plan = JSON.parse(run.dh_execution_plan);
    } catch {
      const { buildPlan } = require('../agents/departmentHead');
      plan = buildPlan(runIdNum);
    }

    // 3. Mark active in memory
    this.activeRuns.set(runIdNum, {
      isPaused: false,
      isCancelled: false,
      currentPhase: 'deep_research',
      currentAgent: null,
    });

    this.emitStatusUpdate(runIdNum, 'deep_research');

    // 4. Resume execution from Phase 2 (deep_research)
    const remainingPhases = (plan.phases || []).filter((p) => p.phase !== 'discovery');
    const remainingPlan = { ...plan, phases: remainingPhases };

    const execPromise = this._executeChain(runIdNum, remainingPlan, options).catch((err) => {
      engine.log('error', `❌ Chain Engine: Post-approval execution error for Run #${runIdNum}: ${err.message}`);
      dbInstance.prepare(`UPDATE research_runs SET status = 'failed', error_summary = ? WHERE id = ?`).run(err.message, runIdNum);
      this.emitStatusUpdate(runIdNum, 'failed');
      this.activeRuns.delete(runIdNum);
    });

    if (options.sync) {
      await execPromise;
      const latestRun = dbInstance.prepare('SELECT status FROM research_runs WHERE id = ?').get(runIdNum);
      return { success: true, status: latestRun?.status || 'completed', run_id: runIdNum };
    }

    return { success: true, status: 'deep_research' };
  }

  /**
   * Pauses an actively running research run.
   * @param {number} runId
   */
  async pauseRun(runId) {
    const runIdNum = Number(runId);
    const ctrl = this.activeRuns.get(runIdNum);
    if (ctrl) {
      ctrl.isPaused = true;
    }
    const dbInstance = db.getDb();
    dbInstance.prepare(`UPDATE research_runs SET status = 'planning', updated_at = datetime('now') WHERE id = ?`).run(runIdNum);
    this.emitStatusUpdate(runIdNum, 'paused');
    return { success: true, status: 'paused' };
  }

  /**
   * Cancels a research run.
   * @param {number} runId
   */
  async cancelRun(runId) {
    const runIdNum = Number(runId);
    const ctrl = this.activeRuns.get(runIdNum);
    if (ctrl) {
      ctrl.isCancelled = true;
    }
    const dbInstance = db.getDb();
    dbInstance.prepare(`UPDATE research_runs SET status = 'cancelled', updated_at = datetime('now') WHERE id = ?`).run(runIdNum);
    this.emitStatusUpdate(runIdNum, 'cancelled');
    this.activeRuns.delete(runIdNum);
    return { success: true, status: 'cancelled' };
  }

  /**
   * Re-evaluates on app launch: cleans up interrupted runs and preserves awaiting_approval.
   */
  async recoverRunsOnStartup() {
    const dbInstance = db.getDb();
    const engine = this.getBrowserEngine();
    const recovered = [];

    // Look for runs left in active intermediate states ('discovery', 'deep_research', 'scoring', 'qa_reporting')
    const interruptedRuns = dbInstance.prepare(`
      SELECT id, status, chain_state 
      FROM research_runs 
      WHERE status IN ('discovery', 'deep_research', 'scoring', 'qa_reporting')
    `).all();

    for (const run of interruptedRuns) {
      engine.log('warn', `🔄 Chain Engine: Run #${run.id} was interrupted during '${run.status}' by app restart. Resetting to paused/planning state.`);
      dbInstance.prepare(`UPDATE research_runs SET status = 'planning', updated_at = datetime('now') WHERE id = ?`).run(run.id);
      recovered.push({ runId: run.id, previousStatus: run.status, resetTo: 'planning' });
    }

    // Runs in 'awaiting_approval' remain intact and ready for user action
    const waitingRuns = dbInstance.prepare(`SELECT id FROM research_runs WHERE status = 'awaiting_approval'`).all();
    if (waitingRuns.length > 0) {
      engine.log('info', `⏳ Chain Engine: ${waitingRuns.length} run(s) are awaiting user approval.`);
    }

    return recovered;
  }

  _saveChainState(runId, stateObj) {
    const dbInstance = db.getDb();
    try {
      dbInstance.prepare(`UPDATE research_runs SET chain_state = ?, updated_at = datetime('now') WHERE id = ?`)
        .run(JSON.stringify(stateObj), runId);
    } catch {
      // ignore
    }
  }

  emitStatusUpdate(runId, status) {
    this.emit('run:status', { runId, status, timestamp: new Date().toISOString() });
    const engine = this.getBrowserEngine();
    if (engine && typeof engine.emit === 'function') {
      engine.emit('run:status', { runId, status });
    }
  }

  emitAgentUpdate(runId, agentNumber, status) {
    this.emit('agent:status', { runId, agentNumber, status, timestamp: new Date().toISOString() });
    const engine = this.getBrowserEngine();
    if (engine && typeof engine.emit === 'function') {
      engine.emit('agent:status', { runId, agentNumber, status });
    }
  }
}

const chainEngineInstance = new ChainEngine();

module.exports = {
  chainEngine: chainEngineInstance,
  ChainEngine,
};
